using System;
using Crystal.Framework;
using static SDL2.SDL;

namespace Crystal.Engine.SFML
{
    public static class ButtonsExtensions
    {
        public static SDL_Scancode ToScancode(this Buttons self)
        {
            switch (self)
            {
                case Buttons.None:
                    return SDL_Scancode.SDL_SCANCODE_UNKNOWN;
                case Buttons.Space:
                    return SDL_Scancode.SDL_SCANCODE_SPACE;
                case Buttons.Apostrophe:
                    return SDL_Scancode.SDL_SCANCODE_APOSTROPHE;
                case Buttons.Comma:
                    return SDL_Scancode.SDL_SCANCODE_COMMA;
                case Buttons.Minus:
                    return SDL_Scancode.SDL_SCANCODE_MINUS;
                case Buttons.Period:
                    return SDL_Scancode.SDL_SCANCODE_PERIOD;
                case Buttons.Slash:
                    return SDL_Scancode.SDL_SCANCODE_SLASH;
                case Buttons.Zero:
                    return SDL_Scancode.SDL_SCANCODE_0;
                case Buttons.One:
                    return SDL_Scancode.SDL_SCANCODE_1;
                case Buttons.Two:
                    return SDL_Scancode.SDL_SCANCODE_2;
                case Buttons.Three:
                    return SDL_Scancode.SDL_SCANCODE_3;
                case Buttons.Four:
                    return SDL_Scancode.SDL_SCANCODE_4;
                case Buttons.Five:
                    return SDL_Scancode.SDL_SCANCODE_5;
                case Buttons.Six:
                    return SDL_Scancode.SDL_SCANCODE_6;
                case Buttons.Seven:
                    return SDL_Scancode.SDL_SCANCODE_7;
                case Buttons.Eight:
                    return SDL_Scancode.SDL_SCANCODE_8;
                case Buttons.Nine:
                    return SDL_Scancode.SDL_SCANCODE_9;
                case Buttons.Semicolon:
                    return SDL_Scancode.SDL_SCANCODE_SEMICOLON;
                case Buttons.Equal:
                    return SDL_Scancode.SDL_SCANCODE_EQUALS;
                case Buttons.A:
                    return SDL_Scancode.SDL_SCANCODE_A;
                case Buttons.B:
                    return SDL_Scancode.SDL_SCANCODE_B;
                case Buttons.C:
                    return SDL_Scancode.SDL_SCANCODE_C;
                case Buttons.D:
                    return SDL_Scancode.SDL_SCANCODE_D;
                case Buttons.E:
                    return SDL_Scancode.SDL_SCANCODE_E;
                case Buttons.F:
                    return SDL_Scancode.SDL_SCANCODE_F;
                case Buttons.G:
                    return SDL_Scancode.SDL_SCANCODE_G;
                case Buttons.H:
                    return SDL_Scancode.SDL_SCANCODE_H;
                case Buttons.I:
                    return SDL_Scancode.SDL_SCANCODE_I;
                case Buttons.J:
                    return SDL_Scancode.SDL_SCANCODE_J;
                case Buttons.K:
                    return SDL_Scancode.SDL_SCANCODE_K;
                case Buttons.L:
                    return SDL_Scancode.SDL_SCANCODE_L;
                case Buttons.M:
                    return SDL_Scancode.SDL_SCANCODE_M;
                case Buttons.N:
                    return SDL_Scancode.SDL_SCANCODE_N;
                case Buttons.O:
                    return SDL_Scancode.SDL_SCANCODE_O;
                case Buttons.P:
                    return SDL_Scancode.SDL_SCANCODE_P;
                case Buttons.Q:
                    return SDL_Scancode.SDL_SCANCODE_Q;
                case Buttons.R:
                    return SDL_Scancode.SDL_SCANCODE_R;
                case Buttons.S:
                    return SDL_Scancode.SDL_SCANCODE_S;
                case Buttons.T:
                    return SDL_Scancode.SDL_SCANCODE_T;
                case Buttons.U:
                    return SDL_Scancode.SDL_SCANCODE_U;
                case Buttons.V:
                    return SDL_Scancode.SDL_SCANCODE_V;
                case Buttons.W:
                    return SDL_Scancode.SDL_SCANCODE_W;
                case Buttons.X:
                    return SDL_Scancode.SDL_SCANCODE_X;
                case Buttons.Y:
                    return SDL_Scancode.SDL_SCANCODE_Y;
                case Buttons.Z:
                    return SDL_Scancode.SDL_SCANCODE_Z;
                case Buttons.LeftBracket:
                    return SDL_Scancode.SDL_SCANCODE_LEFTBRACKET;
                case Buttons.Backslash:
                    return SDL_Scancode.SDL_SCANCODE_BACKSLASH;
                case Buttons.RightBracket:
                    return SDL_Scancode.SDL_SCANCODE_RIGHTBRACKET;
                case Buttons.GraveAccent:
                    return SDL_Scancode.SDL_SCANCODE_GRAVE;
                case Buttons.Escape:
                    return SDL_Scancode.SDL_SCANCODE_ESCAPE;
                case Buttons.Enter:
                    return SDL_Scancode.SDL_SCANCODE_RETURN;
                case Buttons.Tab:
                    return SDL_Scancode.SDL_SCANCODE_TAB;
                case Buttons.Backspace:
                    return SDL_Scancode.SDL_SCANCODE_BACKSPACE;
                case Buttons.Insert:
                    return SDL_Scancode.SDL_SCANCODE_INSERT;
                case Buttons.Delete:
                    return SDL_Scancode.SDL_SCANCODE_DELETE;
                case Buttons.Right:
                    return SDL_Scancode.SDL_SCANCODE_RIGHT;
                case Buttons.Left:
                    return SDL_Scancode.SDL_SCANCODE_LEFT;
                case Buttons.Down:
                    return SDL_Scancode.SDL_SCANCODE_DOWN;
                case Buttons.Up:
                    return SDL_Scancode.SDL_SCANCODE_UP;
                case Buttons.PageUp:
                    return SDL_Scancode.SDL_SCANCODE_PAGEUP;
                case Buttons.PageDown:
                    return SDL_Scancode.SDL_SCANCODE_PAGEDOWN;
                case Buttons.Home:
                    return SDL_Scancode.SDL_SCANCODE_HOME;
                case Buttons.End:
                    return SDL_Scancode.SDL_SCANCODE_END;
                case Buttons.CapsLock:
                    return SDL_Scancode.SDL_SCANCODE_CAPSLOCK;
                case Buttons.ScrollLock:
                    return SDL_Scancode.SDL_SCANCODE_SCROLLLOCK;
                case Buttons.NumLock:
                    return SDL_Scancode.SDL_SCANCODE_NUMLOCKCLEAR;
                case Buttons.PrintScreen:
                    return SDL_Scancode.SDL_SCANCODE_PRINTSCREEN;
                case Buttons.Pause:
                    return SDL_Scancode.SDL_SCANCODE_PAUSE;
                case Buttons.F1:
                    return SDL_Scancode.SDL_SCANCODE_F1;
                case Buttons.F2:
                    return SDL_Scancode.SDL_SCANCODE_F2;
                case Buttons.F3:
                    return SDL_Scancode.SDL_SCANCODE_F3;
                case Buttons.F4:
                    return SDL_Scancode.SDL_SCANCODE_F4;
                case Buttons.F5:
                    return SDL_Scancode.SDL_SCANCODE_F5;
                case Buttons.F6:
                    return SDL_Scancode.SDL_SCANCODE_F6;
                case Buttons.F7:
                    return SDL_Scancode.SDL_SCANCODE_F7;
                case Buttons.F8:
                    return SDL_Scancode.SDL_SCANCODE_F8;
                case Buttons.F9:
                    return SDL_Scancode.SDL_SCANCODE_F9;
                case Buttons.F10:
                    return SDL_Scancode.SDL_SCANCODE_F10;
                case Buttons.F11:
                    return SDL_Scancode.SDL_SCANCODE_F11;
                case Buttons.F12:
                    return SDL_Scancode.SDL_SCANCODE_F12;
                case Buttons.F13:
                    return SDL_Scancode.SDL_SCANCODE_F13;
                case Buttons.F14:
                    return SDL_Scancode.SDL_SCANCODE_F14;
                case Buttons.F15:
                    return SDL_Scancode.SDL_SCANCODE_F15;
                case Buttons.F16:
                    return SDL_Scancode.SDL_SCANCODE_F16;
                case Buttons.F17:
                    return SDL_Scancode.SDL_SCANCODE_F17;
                case Buttons.F18:
                    return SDL_Scancode.SDL_SCANCODE_F18;
                case Buttons.F19:
                    return SDL_Scancode.SDL_SCANCODE_F19;
                case Buttons.F20:
                    return SDL_Scancode.SDL_SCANCODE_F20;
                case Buttons.F21:
                    return SDL_Scancode.SDL_SCANCODE_F21;
                case Buttons.F22:
                    return SDL_Scancode.SDL_SCANCODE_F22;
                case Buttons.F23:
                    return SDL_Scancode.SDL_SCANCODE_F23;
                case Buttons.F24:
                    return SDL_Scancode.SDL_SCANCODE_F24;
                case Buttons.KeypadZero:
                    return SDL_Scancode.SDL_SCANCODE_KP_0;
                case Buttons.KeypadOne:
                    return SDL_Scancode.SDL_SCANCODE_KP_1;
                case Buttons.KeypadTwo:
                    return SDL_Scancode.SDL_SCANCODE_KP_2;
                case Buttons.KeypadThree:
                    return SDL_Scancode.SDL_SCANCODE_KP_3;
                case Buttons.KeypadFour:
                    return SDL_Scancode.SDL_SCANCODE_KP_4;
                case Buttons.KeypadFive:
                    return SDL_Scancode.SDL_SCANCODE_KP_5;
                case Buttons.KeypadSix:
                    return SDL_Scancode.SDL_SCANCODE_KP_6;
                case Buttons.KeypadSeven:
                    return SDL_Scancode.SDL_SCANCODE_KP_7;
                case Buttons.KeypadEight:
                    return SDL_Scancode.SDL_SCANCODE_KP_8;
                case Buttons.KeypadNine:
                    return SDL_Scancode.SDL_SCANCODE_KP_9;
                case Buttons.KeypadDecimal:
                    return SDL_Scancode.SDL_SCANCODE_KP_DECIMAL;
                case Buttons.KeypadDivide:
                    return SDL_Scancode.SDL_SCANCODE_KP_DIVIDE;
                case Buttons.KeypadMultiply:
                    return SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY;
                case Buttons.KeypadSubtract:
                    return SDL_Scancode.SDL_SCANCODE_KP_MINUS;
                case Buttons.KeypadAdd:
                    return SDL_Scancode.SDL_SCANCODE_KP_PLUS;
                case Buttons.KeypadEnter:
                    return SDL_Scancode.SDL_SCANCODE_KP_ENTER;
                case Buttons.KeypadEqual:
                    return SDL_Scancode.SDL_SCANCODE_KP_EQUALS;
                case Buttons.LeftShift:
                    return SDL_Scancode.SDL_SCANCODE_LSHIFT;
                case Buttons.LeftControl:
                    return SDL_Scancode.SDL_SCANCODE_LCTRL;
                case Buttons.LeftAlt:
                    return SDL_Scancode.SDL_SCANCODE_LALT;
                case Buttons.LeftSuper:
                    return SDL_Scancode.SDL_SCANCODE_LGUI;
                case Buttons.RightShift:
                    return SDL_Scancode.SDL_SCANCODE_RSHIFT;
                case Buttons.RightControl:
                    return SDL_Scancode.SDL_SCANCODE_RCTRL;
                case Buttons.RightAlt:
                    return SDL_Scancode.SDL_SCANCODE_RALT;
                case Buttons.RightSuper:
                    return SDL_Scancode.SDL_SCANCODE_RGUI;
                default:
                    return SDL_Scancode.SDL_SCANCODE_UNKNOWN;
            }
        }

        public static SDL_Keycode ToKeycode(this Buttons self)
        {
            switch (self)
            {
                case Buttons.None:
                    return SDL_Keycode.SDLK_UNKNOWN;
                case Buttons.Space:
                    return SDL_Keycode.SDLK_SPACE;
                case Buttons.Apostrophe:
                    return SDL_Keycode.SDLK_QUOTE;
                case Buttons.Comma:
                    return SDL_Keycode.SDLK_COMMA;
                case Buttons.Minus:
                    return SDL_Keycode.SDLK_MINUS;
                case Buttons.Period:
                    return SDL_Keycode.SDLK_PERIOD;
                case Buttons.Slash:
                    return SDL_Keycode.SDLK_SLASH;
                case Buttons.Zero:
                    return SDL_Keycode.SDLK_0;
                case Buttons.One:
                    return SDL_Keycode.SDLK_1;
                case Buttons.Two:
                    return SDL_Keycode.SDLK_2;
                case Buttons.Three:
                    return SDL_Keycode.SDLK_3;
                case Buttons.Four:
                    return SDL_Keycode.SDLK_4;
                case Buttons.Five:
                    return SDL_Keycode.SDLK_5;
                case Buttons.Six:
                    return SDL_Keycode.SDLK_6;
                case Buttons.Seven:
                    return SDL_Keycode.SDLK_7;
                case Buttons.Eight:
                    return SDL_Keycode.SDLK_8;
                case Buttons.Nine:
                    return SDL_Keycode.SDLK_9;
                case Buttons.Semicolon:
                    return SDL_Keycode.SDLK_SEMICOLON;
                case Buttons.Equal:
                    return SDL_Keycode.SDLK_EQUALS;
                case Buttons.A:
                    return SDL_Keycode.SDLK_a;
                case Buttons.B:
                    return SDL_Keycode.SDLK_b;
                case Buttons.C:
                    return SDL_Keycode.SDLK_c;
                case Buttons.D:
                    return SDL_Keycode.SDLK_d;
                case Buttons.E:
                    return SDL_Keycode.SDLK_e;
                case Buttons.F:
                    return SDL_Keycode.SDLK_f;
                case Buttons.G:
                    return SDL_Keycode.SDLK_g;
                case Buttons.H:
                    return SDL_Keycode.SDLK_h;
                case Buttons.I:
                    return SDL_Keycode.SDLK_i;
                case Buttons.J:
                    return SDL_Keycode.SDLK_j;
                case Buttons.K:
                    return SDL_Keycode.SDLK_k;
                case Buttons.L:
                    return SDL_Keycode.SDLK_l;
                case Buttons.M:
                    return SDL_Keycode.SDLK_m;
                case Buttons.N:
                    return SDL_Keycode.SDLK_n;
                case Buttons.O:
                    return SDL_Keycode.SDLK_o;
                case Buttons.P:
                    return SDL_Keycode.SDLK_p;
                case Buttons.Q:
                    return SDL_Keycode.SDLK_q;
                case Buttons.R:
                    return SDL_Keycode.SDLK_r;
                case Buttons.S:
                    return SDL_Keycode.SDLK_s;
                case Buttons.T:
                    return SDL_Keycode.SDLK_t;
                case Buttons.U:
                    return SDL_Keycode.SDLK_u;
                case Buttons.V:
                    return SDL_Keycode.SDLK_v;
                case Buttons.W:
                    return SDL_Keycode.SDLK_w;
                case Buttons.X:
                    return SDL_Keycode.SDLK_x;
                case Buttons.Y:
                    return SDL_Keycode.SDLK_y;
                case Buttons.Z:
                    return SDL_Keycode.SDLK_z;
                case Buttons.LeftBracket:
                    return SDL_Keycode.SDLK_LEFTBRACKET;
                case Buttons.Backslash:
                    return SDL_Keycode.SDLK_BACKSLASH;
                case Buttons.RightBracket:
                    return SDL_Keycode.SDLK_RIGHTBRACKET;
                case Buttons.GraveAccent:
                    return SDL_Keycode.SDLK_BACKQUOTE;
                case Buttons.Escape:
                    return SDL_Keycode.SDLK_ESCAPE;
                case Buttons.Enter:
                    return SDL_Keycode.SDLK_RETURN;
                case Buttons.Tab:
                    return SDL_Keycode.SDLK_TAB;
                case Buttons.Backspace:
                    return SDL_Keycode.SDLK_BACKSPACE;
                case Buttons.Insert:
                    return SDL_Keycode.SDLK_INSERT;
                case Buttons.Delete:
                    return SDL_Keycode.SDLK_DELETE;
                case Buttons.Right:
                    return SDL_Keycode.SDLK_RIGHT;
                case Buttons.Left:
                    return SDL_Keycode.SDLK_LEFT;
                case Buttons.Down:
                    return SDL_Keycode.SDLK_DOWN;
                case Buttons.Up:
                    return SDL_Keycode.SDLK_UP;
                case Buttons.PageUp:
                    return SDL_Keycode.SDLK_PAGEUP;
                case Buttons.PageDown:
                    return SDL_Keycode.SDLK_PAGEDOWN;
                case Buttons.Home:
                    return SDL_Keycode.SDLK_HOME;
                case Buttons.End:
                    return SDL_Keycode.SDLK_END;
                case Buttons.CapsLock:
                    return SDL_Keycode.SDLK_CAPSLOCK;
                case Buttons.ScrollLock:
                    return SDL_Keycode.SDLK_SCROLLLOCK;
                case Buttons.NumLock:
                    return SDL_Keycode.SDLK_NUMLOCKCLEAR;
                case Buttons.PrintScreen:
                    return SDL_Keycode.SDLK_PRINTSCREEN;
                case Buttons.Pause:
                    return SDL_Keycode.SDLK_PAUSE;
                case Buttons.F1:
                    return SDL_Keycode.SDLK_F1;
                case Buttons.F2:
                    return SDL_Keycode.SDLK_F2;
                case Buttons.F3:
                    return SDL_Keycode.SDLK_F3;
                case Buttons.F4:
                    return SDL_Keycode.SDLK_F4;
                case Buttons.F5:
                    return SDL_Keycode.SDLK_F5;
                case Buttons.F6:
                    return SDL_Keycode.SDLK_F6;
                case Buttons.F7:
                    return SDL_Keycode.SDLK_F7;
                case Buttons.F8:
                    return SDL_Keycode.SDLK_F8;
                case Buttons.F9:
                    return SDL_Keycode.SDLK_F9;
                case Buttons.F10:
                    return SDL_Keycode.SDLK_F10;
                case Buttons.F11:
                    return SDL_Keycode.SDLK_F11;
                case Buttons.F12:
                    return SDL_Keycode.SDLK_F12;
                case Buttons.F13:
                    return SDL_Keycode.SDLK_F13;
                case Buttons.F14:
                    return SDL_Keycode.SDLK_F14;
                case Buttons.F15:
                    return SDL_Keycode.SDLK_F15;
                case Buttons.F16:
                    return SDL_Keycode.SDLK_F16;
                case Buttons.F17:
                    return SDL_Keycode.SDLK_F17;
                case Buttons.F18:
                    return SDL_Keycode.SDLK_F18;
                case Buttons.F19:
                    return SDL_Keycode.SDLK_F19;
                case Buttons.F20:
                    return SDL_Keycode.SDLK_F20;
                case Buttons.F21:
                    return SDL_Keycode.SDLK_F21;
                case Buttons.F22:
                    return SDL_Keycode.SDLK_F22;
                case Buttons.F23:
                    return SDL_Keycode.SDLK_F23;
                case Buttons.F24:
                    return SDL_Keycode.SDLK_F24;
                case Buttons.KeypadZero:
                    return SDL_Keycode.SDLK_KP_0;
                case Buttons.KeypadOne:
                    return SDL_Keycode.SDLK_KP_1;
                case Buttons.KeypadTwo:
                    return SDL_Keycode.SDLK_KP_2;
                case Buttons.KeypadThree:
                    return SDL_Keycode.SDLK_KP_3;
                case Buttons.KeypadFour:
                    return SDL_Keycode.SDLK_KP_4;
                case Buttons.KeypadFive:
                    return SDL_Keycode.SDLK_KP_5;
                case Buttons.KeypadSix:
                    return SDL_Keycode.SDLK_KP_6;
                case Buttons.KeypadSeven:
                    return SDL_Keycode.SDLK_KP_7;
                case Buttons.KeypadEight:
                    return SDL_Keycode.SDLK_KP_8;
                case Buttons.KeypadNine:
                    return SDL_Keycode.SDLK_KP_9;
                case Buttons.KeypadDecimal:
                    return SDL_Keycode.SDLK_KP_DECIMAL;
                case Buttons.KeypadDivide:
                    return SDL_Keycode.SDLK_KP_DIVIDE;
                case Buttons.KeypadMultiply:
                    return SDL_Keycode.SDLK_KP_MULTIPLY;
                case Buttons.KeypadSubtract:
                    return SDL_Keycode.SDLK_KP_MINUS;
                case Buttons.KeypadAdd:
                    return SDL_Keycode.SDLK_KP_PLUS;
                case Buttons.KeypadEnter:
                    return SDL_Keycode.SDLK_KP_ENTER;
                case Buttons.KeypadEqual:
                    return SDL_Keycode.SDLK_KP_EQUALS;
                case Buttons.LeftShift:
                    return SDL_Keycode.SDLK_LSHIFT;
                case Buttons.LeftControl:
                    return SDL_Keycode.SDLK_LCTRL;
                case Buttons.LeftAlt:
                    return SDL_Keycode.SDLK_LALT;
                case Buttons.LeftSuper:
                    return SDL_Keycode.SDLK_LGUI;
                case Buttons.RightShift:
                    return SDL_Keycode.SDLK_RSHIFT;
                case Buttons.RightControl:
                    return SDL_Keycode.SDLK_RCTRL;
                case Buttons.RightAlt:
                    return SDL_Keycode.SDLK_RALT;
                case Buttons.RightSuper:
                    return SDL_Keycode.SDLK_RGUI;
                default:
                    return SDL_Keycode.SDLK_UNKNOWN;
            }
        }

        public static Buttons ToCrystal(this SDL_Scancode self)
        {
            switch (self)
            {
                case SDL_Scancode.SDL_SCANCODE_UNKNOWN:
                    return Buttons.None;
                case SDL_Scancode.SDL_SCANCODE_SPACE:
                    return Buttons.Space;
                case SDL_Scancode.SDL_SCANCODE_APOSTROPHE:
                    return Buttons.Apostrophe;
                case SDL_Scancode.SDL_SCANCODE_COMMA:
                    return Buttons.Comma;
                case SDL_Scancode.SDL_SCANCODE_MINUS:
                    return Buttons.Minus;
                case SDL_Scancode.SDL_SCANCODE_PERIOD:
                    return Buttons.Period;
                case SDL_Scancode.SDL_SCANCODE_SLASH:
                    return Buttons.Slash;
                case SDL_Scancode.SDL_SCANCODE_0:
                    return Buttons.Zero;
                case SDL_Scancode.SDL_SCANCODE_1:
                    return Buttons.One;
                case SDL_Scancode.SDL_SCANCODE_2:
                    return Buttons.Two;
                case SDL_Scancode.SDL_SCANCODE_3:
                    return Buttons.Three;
                case SDL_Scancode.SDL_SCANCODE_4:
                    return Buttons.Four;
                case SDL_Scancode.SDL_SCANCODE_5:
                    return Buttons.Five;
                case SDL_Scancode.SDL_SCANCODE_6:
                    return Buttons.Six;
                case SDL_Scancode.SDL_SCANCODE_7:
                    return Buttons.Seven;
                case SDL_Scancode.SDL_SCANCODE_8:
                    return Buttons.Eight;
                case SDL_Scancode.SDL_SCANCODE_9:
                    return Buttons.Nine;
                case SDL_Scancode.SDL_SCANCODE_SEMICOLON:
                    return Buttons.Semicolon;
                case SDL_Scancode.SDL_SCANCODE_EQUALS:
                    return Buttons.Equal;
                case SDL_Scancode.SDL_SCANCODE_A:
                    return Buttons.A;
                case SDL_Scancode.SDL_SCANCODE_B:
                    return Buttons.B;
                case SDL_Scancode.SDL_SCANCODE_C:
                    return Buttons.C;
                case SDL_Scancode.SDL_SCANCODE_D:
                    return Buttons.D;
                case SDL_Scancode.SDL_SCANCODE_E:
                    return Buttons.E;
                case SDL_Scancode.SDL_SCANCODE_F:
                    return Buttons.F;
                case SDL_Scancode.SDL_SCANCODE_G:
                    return Buttons.G;
                case SDL_Scancode.SDL_SCANCODE_H:
                    return Buttons.H;
                case SDL_Scancode.SDL_SCANCODE_I:
                    return Buttons.I;
                case SDL_Scancode.SDL_SCANCODE_J:
                    return Buttons.J;
                case SDL_Scancode.SDL_SCANCODE_K:
                    return Buttons.K;
                case SDL_Scancode.SDL_SCANCODE_L:
                    return Buttons.L;
                case SDL_Scancode.SDL_SCANCODE_M:
                    return Buttons.M;
                case SDL_Scancode.SDL_SCANCODE_N:
                    return Buttons.N;
                case SDL_Scancode.SDL_SCANCODE_O:
                    return Buttons.O;
                case SDL_Scancode.SDL_SCANCODE_P:
                    return Buttons.P;
                case SDL_Scancode.SDL_SCANCODE_Q:
                    return Buttons.Q;
                case SDL_Scancode.SDL_SCANCODE_R:
                    return Buttons.R;
                case SDL_Scancode.SDL_SCANCODE_S:
                    return Buttons.S;
                case SDL_Scancode.SDL_SCANCODE_T:
                    return Buttons.T;
                case SDL_Scancode.SDL_SCANCODE_U:
                    return Buttons.U;
                case SDL_Scancode.SDL_SCANCODE_V:
                    return Buttons.V;
                case SDL_Scancode.SDL_SCANCODE_W:
                    return Buttons.W;
                case SDL_Scancode.SDL_SCANCODE_X:
                    return Buttons.X;
                case SDL_Scancode.SDL_SCANCODE_Y:
                    return Buttons.Y;
                case SDL_Scancode.SDL_SCANCODE_Z:
                    return Buttons.Z;
                case SDL_Scancode.SDL_SCANCODE_LEFTBRACKET:
                    return Buttons.LeftBracket;
                case SDL_Scancode.SDL_SCANCODE_BACKSLASH:
                    return Buttons.Backslash;
                case SDL_Scancode.SDL_SCANCODE_RIGHTBRACKET:
                    return Buttons.RightBracket;
                case SDL_Scancode.SDL_SCANCODE_GRAVE:
                    return Buttons.GraveAccent;
                case SDL_Scancode.SDL_SCANCODE_ESCAPE:
                    return Buttons.Escape;
                case SDL_Scancode.SDL_SCANCODE_RETURN:
                    return Buttons.Enter;
                case SDL_Scancode.SDL_SCANCODE_TAB:
                    return Buttons.Tab;
                case SDL_Scancode.SDL_SCANCODE_BACKSPACE:
                    return Buttons.Backspace;
                case SDL_Scancode.SDL_SCANCODE_INSERT:
                    return Buttons.Insert;
                case SDL_Scancode.SDL_SCANCODE_DELETE:
                    return Buttons.Delete;
                case SDL_Scancode.SDL_SCANCODE_RIGHT:
                    return Buttons.Right;
                case SDL_Scancode.SDL_SCANCODE_LEFT:
                    return Buttons.Left;
                case SDL_Scancode.SDL_SCANCODE_DOWN:
                    return Buttons.Down;
                case SDL_Scancode.SDL_SCANCODE_UP:
                    return Buttons.Up;
                case SDL_Scancode.SDL_SCANCODE_PAGEUP:
                    return Buttons.PageUp;
                case SDL_Scancode.SDL_SCANCODE_PAGEDOWN:
                    return Buttons.PageDown;
                case SDL_Scancode.SDL_SCANCODE_HOME:
                    return Buttons.Home;
                case SDL_Scancode.SDL_SCANCODE_END:
                    return Buttons.End;
                case SDL_Scancode.SDL_SCANCODE_CAPSLOCK:
                    return Buttons.CapsLock;
                case SDL_Scancode.SDL_SCANCODE_SCROLLLOCK:
                    return Buttons.ScrollLock;
                case SDL_Scancode.SDL_SCANCODE_NUMLOCKCLEAR:
                    return Buttons.NumLock;
                case SDL_Scancode.SDL_SCANCODE_PRINTSCREEN:
                    return Buttons.PrintScreen;
                case SDL_Scancode.SDL_SCANCODE_PAUSE:
                    return Buttons.Pause;
                case SDL_Scancode.SDL_SCANCODE_F1:
                    return Buttons.F1;
                case SDL_Scancode.SDL_SCANCODE_F2:
                    return Buttons.F2;
                case SDL_Scancode.SDL_SCANCODE_F3:
                    return Buttons.F3;
                case SDL_Scancode.SDL_SCANCODE_F4:
                    return Buttons.F4;
                case SDL_Scancode.SDL_SCANCODE_F5:
                    return Buttons.F5;
                case SDL_Scancode.SDL_SCANCODE_F6:
                    return Buttons.F6;
                case SDL_Scancode.SDL_SCANCODE_F7:
                    return Buttons.F7;
                case SDL_Scancode.SDL_SCANCODE_F8:
                    return Buttons.F8;
                case SDL_Scancode.SDL_SCANCODE_F9:
                    return Buttons.F9;
                case SDL_Scancode.SDL_SCANCODE_F10:
                    return Buttons.F10;
                case SDL_Scancode.SDL_SCANCODE_F11:
                    return Buttons.F11;
                case SDL_Scancode.SDL_SCANCODE_F12:
                    return Buttons.F12;
                case SDL_Scancode.SDL_SCANCODE_F13:
                    return Buttons.F13;
                case SDL_Scancode.SDL_SCANCODE_F14:
                    return Buttons.F14;
                case SDL_Scancode.SDL_SCANCODE_F15:
                    return Buttons.F15;
                case SDL_Scancode.SDL_SCANCODE_F16:
                    return Buttons.F16;
                case SDL_Scancode.SDL_SCANCODE_F17:
                    return Buttons.F17;
                case SDL_Scancode.SDL_SCANCODE_F18:
                    return Buttons.F18;
                case SDL_Scancode.SDL_SCANCODE_F19:
                    return Buttons.F19;
                case SDL_Scancode.SDL_SCANCODE_F20:
                    return Buttons.F20;
                case SDL_Scancode.SDL_SCANCODE_F21:
                    return Buttons.F21;
                case SDL_Scancode.SDL_SCANCODE_F22:
                    return Buttons.F22;
                case SDL_Scancode.SDL_SCANCODE_F23:
                    return Buttons.F23;
                case SDL_Scancode.SDL_SCANCODE_F24:
                    return Buttons.F24;
                case SDL_Scancode.SDL_SCANCODE_KP_0:
                    return Buttons.KeypadZero;
                case SDL_Scancode.SDL_SCANCODE_KP_1:
                    return Buttons.KeypadOne;
                case SDL_Scancode.SDL_SCANCODE_KP_2:
                    return Buttons.KeypadTwo;
                case SDL_Scancode.SDL_SCANCODE_KP_3:
                    return Buttons.KeypadThree;
                case SDL_Scancode.SDL_SCANCODE_KP_4:
                    return Buttons.KeypadFour;
                case SDL_Scancode.SDL_SCANCODE_KP_5:
                    return Buttons.KeypadFive;
                case SDL_Scancode.SDL_SCANCODE_KP_6:
                    return Buttons.KeypadSix;
                case SDL_Scancode.SDL_SCANCODE_KP_7:
                    return Buttons.KeypadSeven;
                case SDL_Scancode.SDL_SCANCODE_KP_8:
                    return Buttons.KeypadEight;
                case SDL_Scancode.SDL_SCANCODE_KP_9:
                    return Buttons.KeypadNine;
                case SDL_Scancode.SDL_SCANCODE_KP_DECIMAL:
                    return Buttons.KeypadDecimal;
                case SDL_Scancode.SDL_SCANCODE_KP_DIVIDE:
                    return Buttons.KeypadDivide;
                case SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY:
                    return Buttons.KeypadMultiply;
                case SDL_Scancode.SDL_SCANCODE_KP_MINUS:
                    return Buttons.KeypadSubtract;
                case SDL_Scancode.SDL_SCANCODE_KP_PLUS:
                    return Buttons.KeypadAdd;
                case SDL_Scancode.SDL_SCANCODE_KP_ENTER:
                    return Buttons.KeypadEnter;
                case SDL_Scancode.SDL_SCANCODE_KP_EQUALS:
                    return Buttons.KeypadEqual;
                case SDL_Scancode.SDL_SCANCODE_LSHIFT:
                    return Buttons.LeftShift;
                case SDL_Scancode.SDL_SCANCODE_LCTRL:
                    return Buttons.LeftControl;
                case SDL_Scancode.SDL_SCANCODE_LALT:
                    return Buttons.LeftAlt;
                case SDL_Scancode.SDL_SCANCODE_LGUI:
                    return Buttons.LeftSuper;
                case SDL_Scancode.SDL_SCANCODE_RSHIFT:
                    return Buttons.RightShift;
                case SDL_Scancode.SDL_SCANCODE_RCTRL:
                    return Buttons.RightControl;
                case SDL_Scancode.SDL_SCANCODE_RALT:
                    return Buttons.RightAlt;
                case SDL_Scancode.SDL_SCANCODE_RGUI:
                    return Buttons.RightSuper;
                default:
                    return Buttons.None;
            }
        }

        public static Buttons ToCrystal(this SDL_Keycode self)
        {
            switch (self)
            {
                case SDL_Keycode.SDLK_UNKNOWN:
                    return Buttons.None;
                case SDL_Keycode.SDLK_SPACE:
                    return Buttons.Space;
                case SDL_Keycode.SDLK_QUOTE:
                    return Buttons.Apostrophe;
                case SDL_Keycode.SDLK_COMMA:
                    return Buttons.Comma;
                case SDL_Keycode.SDLK_MINUS:
                    return Buttons.Minus;
                case SDL_Keycode.SDLK_PERIOD:
                    return Buttons.Period;
                case SDL_Keycode.SDLK_SLASH:
                    return Buttons.Slash;
                case SDL_Keycode.SDLK_0:
                    return Buttons.Zero;
                case SDL_Keycode.SDLK_1:
                    return Buttons.One;
                case SDL_Keycode.SDLK_2:
                    return Buttons.Two;
                case SDL_Keycode.SDLK_3:
                    return Buttons.Three;
                case SDL_Keycode.SDLK_4:
                    return Buttons.Four;
                case SDL_Keycode.SDLK_5:
                    return Buttons.Five;
                case SDL_Keycode.SDLK_6:
                    return Buttons.Six;
                case SDL_Keycode.SDLK_7:
                    return Buttons.Seven;
                case SDL_Keycode.SDLK_8:
                    return Buttons.Eight;
                case SDL_Keycode.SDLK_9:
                    return Buttons.Nine;
                case SDL_Keycode.SDLK_SEMICOLON:
                    return Buttons.Semicolon;
                case SDL_Keycode.SDLK_EQUALS:
                    return Buttons.Equal;
                case SDL_Keycode.SDLK_a:
                    return Buttons.A;
                case SDL_Keycode.SDLK_b:
                    return Buttons.B;
                case SDL_Keycode.SDLK_c:
                    return Buttons.C;
                case SDL_Keycode.SDLK_d:
                    return Buttons.D;
                case SDL_Keycode.SDLK_e:
                    return Buttons.E;
                case SDL_Keycode.SDLK_f:
                    return Buttons.F;
                case SDL_Keycode.SDLK_g:
                    return Buttons.G;
                case SDL_Keycode.SDLK_h:
                    return Buttons.H;
                case SDL_Keycode.SDLK_i:
                    return Buttons.I;
                case SDL_Keycode.SDLK_j:
                    return Buttons.J;
                case SDL_Keycode.SDLK_k:
                    return Buttons.K;
                case SDL_Keycode.SDLK_l:
                    return Buttons.L;
                case SDL_Keycode.SDLK_m:
                    return Buttons.M;
                case SDL_Keycode.SDLK_n:
                    return Buttons.N;
                case SDL_Keycode.SDLK_o:
                    return Buttons.O;
                case SDL_Keycode.SDLK_p:
                    return Buttons.P;
                case SDL_Keycode.SDLK_q:
                    return Buttons.Q;
                case SDL_Keycode.SDLK_r:
                    return Buttons.R;
                case SDL_Keycode.SDLK_s:
                    return Buttons.S;
                case SDL_Keycode.SDLK_t:
                    return Buttons.T;
                case SDL_Keycode.SDLK_u:
                    return Buttons.U;
                case SDL_Keycode.SDLK_v:
                    return Buttons.V;
                case SDL_Keycode.SDLK_w:
                    return Buttons.W;
                case SDL_Keycode.SDLK_x:
                    return Buttons.X;
                case SDL_Keycode.SDLK_y:
                    return Buttons.Y;
                case SDL_Keycode.SDLK_z:
                    return Buttons.Z;
                case SDL_Keycode.SDLK_LEFTBRACKET:
                    return Buttons.LeftBracket;
                case SDL_Keycode.SDLK_BACKSLASH:
                    return Buttons.Backslash;
                case SDL_Keycode.SDLK_RIGHTBRACKET:
                    return Buttons.RightBracket;
                case SDL_Keycode.SDLK_BACKQUOTE:
                    return Buttons.GraveAccent;
                case SDL_Keycode.SDLK_ESCAPE:
                    return Buttons.Escape;
                case SDL_Keycode.SDLK_RETURN:
                    return Buttons.Enter;
                case SDL_Keycode.SDLK_TAB:
                    return Buttons.Tab;
                case SDL_Keycode.SDLK_BACKSPACE:
                    return Buttons.Backspace;
                case SDL_Keycode.SDLK_INSERT:
                    return Buttons.Insert;
                case SDL_Keycode.SDLK_DELETE:
                    return Buttons.Delete;
                case SDL_Keycode.SDLK_RIGHT:
                    return Buttons.Right;
                case SDL_Keycode.SDLK_LEFT:
                    return Buttons.Left;
                case SDL_Keycode.SDLK_DOWN:
                    return Buttons.Down;
                case SDL_Keycode.SDLK_UP:
                    return Buttons.Up;
                case SDL_Keycode.SDLK_PAGEUP:
                    return Buttons.PageUp;
                case SDL_Keycode.SDLK_PAGEDOWN:
                    return Buttons.PageDown;
                case SDL_Keycode.SDLK_HOME:
                    return Buttons.Home;
                case SDL_Keycode.SDLK_END:
                    return Buttons.End;
                case SDL_Keycode.SDLK_CAPSLOCK:
                    return Buttons.CapsLock;
                case SDL_Keycode.SDLK_SCROLLLOCK:
                    return Buttons.ScrollLock;
                case SDL_Keycode.SDLK_NUMLOCKCLEAR:
                    return Buttons.NumLock;
                case SDL_Keycode.SDLK_PRINTSCREEN:
                    return Buttons.PrintScreen;
                case SDL_Keycode.SDLK_PAUSE:
                    return Buttons.Pause;
                case SDL_Keycode.SDLK_F1:
                    return Buttons.F1;
                case SDL_Keycode.SDLK_F2:
                    return Buttons.F2;
                case SDL_Keycode.SDLK_F3:
                    return Buttons.F3;
                case SDL_Keycode.SDLK_F4:
                    return Buttons.F4;
                case SDL_Keycode.SDLK_F5:
                    return Buttons.F5;
                case SDL_Keycode.SDLK_F6:
                    return Buttons.F6;
                case SDL_Keycode.SDLK_F7:
                    return Buttons.F7;
                case SDL_Keycode.SDLK_F8:
                    return Buttons.F8;
                case SDL_Keycode.SDLK_F9:
                    return Buttons.F9;
                case SDL_Keycode.SDLK_F10:
                    return Buttons.F10;
                case SDL_Keycode.SDLK_F11:
                    return Buttons.F11;
                case SDL_Keycode.SDLK_F12:
                    return Buttons.F12;
                case SDL_Keycode.SDLK_F13:
                    return Buttons.F13;
                case SDL_Keycode.SDLK_F14:
                    return Buttons.F14;
                case SDL_Keycode.SDLK_F15:
                    return Buttons.F15;
                case SDL_Keycode.SDLK_F16:
                    return Buttons.F16;
                case SDL_Keycode.SDLK_F17:
                    return Buttons.F17;
                case SDL_Keycode.SDLK_F18:
                    return Buttons.F18;
                case SDL_Keycode.SDLK_F19:
                    return Buttons.F19;
                case SDL_Keycode.SDLK_F20:
                    return Buttons.F20;
                case SDL_Keycode.SDLK_F21:
                    return Buttons.F21;
                case SDL_Keycode.SDLK_F22:
                    return Buttons.F22;
                case SDL_Keycode.SDLK_F23:
                    return Buttons.F23;
                case SDL_Keycode.SDLK_F24:
                    return Buttons.F24;
                case SDL_Keycode.SDLK_KP_0:
                    return Buttons.KeypadZero;
                case SDL_Keycode.SDLK_KP_1:
                    return Buttons.KeypadOne;
                case SDL_Keycode.SDLK_KP_2:
                    return Buttons.KeypadTwo;
                case SDL_Keycode.SDLK_KP_3:
                    return Buttons.KeypadThree;
                case SDL_Keycode.SDLK_KP_4:
                    return Buttons.KeypadFour;
                case SDL_Keycode.SDLK_KP_5:
                    return Buttons.KeypadFive;
                case SDL_Keycode.SDLK_KP_6:
                    return Buttons.KeypadSix;
                case SDL_Keycode.SDLK_KP_7:
                    return Buttons.KeypadSeven;
                case SDL_Keycode.SDLK_KP_8:
                    return Buttons.KeypadEight;
                case SDL_Keycode.SDLK_KP_9:
                    return Buttons.KeypadNine;
                case SDL_Keycode.SDLK_KP_DECIMAL:
                    return Buttons.KeypadDecimal;
                case SDL_Keycode.SDLK_KP_DIVIDE:
                    return Buttons.KeypadDivide;
                case SDL_Keycode.SDLK_KP_MULTIPLY:
                    return Buttons.KeypadMultiply;
                case SDL_Keycode.SDLK_KP_MINUS:
                    return Buttons.KeypadSubtract;
                case SDL_Keycode.SDLK_KP_PLUS:
                    return Buttons.KeypadAdd;
                case SDL_Keycode.SDLK_KP_ENTER:
                    return Buttons.KeypadEnter;
                case SDL_Keycode.SDLK_KP_EQUALS:
                    return Buttons.KeypadEqual;
                case SDL_Keycode.SDLK_LSHIFT:
                    return Buttons.LeftShift;
                case SDL_Keycode.SDLK_LCTRL:
                    return Buttons.LeftControl;
                case SDL_Keycode.SDLK_LALT:
                    return Buttons.LeftAlt;
                case SDL_Keycode.SDLK_LGUI:
                    return Buttons.LeftSuper;
                case SDL_Keycode.SDLK_RSHIFT:
                    return Buttons.RightShift;
                case SDL_Keycode.SDLK_RCTRL:
                    return Buttons.RightControl;
                case SDL_Keycode.SDLK_RALT:
                    return Buttons.RightAlt;
                case SDL_Keycode.SDLK_RGUI:
                    return Buttons.RightSuper;
                default:
                    return Buttons.None;
            }
        }
    }
}