using KeysAndButtons = Crystal.Framework.Buttons;
using Microsoft.Xna.Framework.Input;

namespace Crystal.Engine
{
    public static class ButtonsExtensions
    {
        public static Keys ToMonoGame(this KeysAndButtons self)
        {
            switch(self)
            {
                case KeysAndButtons.Apostrophe:
                    return Keys.OemQuotes;
                case KeysAndButtons.Comma:
                    return Keys.OemComma;
                case KeysAndButtons.Minus:
                    return Keys.OemMinus;
                case KeysAndButtons.Period:
                    return Keys.OemPeriod;
                case KeysAndButtons.Slash:
                    return Keys.OemQuestion;
                case KeysAndButtons.Zero:
                    return Keys.D0;
                case KeysAndButtons.One:
                    return Keys.D1;
                case KeysAndButtons.Two:
                    return Keys.D2;
                case KeysAndButtons.Three:
                    return Keys.D3;
                case KeysAndButtons.Four:
                    return Keys.D4;
                case KeysAndButtons.Five:
                    return Keys.D5;
                case KeysAndButtons.Six:
                    return Keys.D6;
                case KeysAndButtons.Seven:
                    return Keys.D7;
                case KeysAndButtons.Eight:
                    return Keys.D8;
                case KeysAndButtons.Nine:
                    return Keys.D9;
                case KeysAndButtons.Semicolon:
                    return Keys.OemSemicolon;
                case KeysAndButtons.Equal:
                    return Keys.OemPlus;
                case KeysAndButtons.A:
                    return Keys.A;
                case KeysAndButtons.B:
                    return Keys.B;
                case KeysAndButtons.C:
                    return Keys.C;
                case KeysAndButtons.D:
                    return Keys.D;
                case KeysAndButtons.E:
                    return Keys.E;
                case KeysAndButtons.F:
                    return Keys.F;
                case KeysAndButtons.G:
                    return Keys.G;
                case KeysAndButtons.H:
                    return Keys.H;
                case KeysAndButtons.I:
                    return Keys.I;
                case KeysAndButtons.J:
                    return Keys.J;
                case KeysAndButtons.K:
                    return Keys.K;
                case KeysAndButtons.L:
                    return Keys.L;
                case KeysAndButtons.M:
                    return Keys.M;
                case KeysAndButtons.N:
                    return Keys.N;
                case KeysAndButtons.O:
                    return Keys.O;
                case KeysAndButtons.P:
                    return Keys.P;
                case KeysAndButtons.Q:
                    return Keys.Q;
                case KeysAndButtons.R:
                    return Keys.R;
                case KeysAndButtons.S:
                    return Keys.S;
                case KeysAndButtons.T:
                    return Keys.T;
                case KeysAndButtons.U:
                    return Keys.U;
                case KeysAndButtons.V:
                    return Keys.V;
                case KeysAndButtons.W:
                    return Keys.W;
                case KeysAndButtons.X:
                    return Keys.X;
                case KeysAndButtons.Y:
                    return Keys.Y;
                case KeysAndButtons.Z:
                    return Keys.Z;
                case KeysAndButtons.LeftBracket:
                    return Keys.OemOpenBrackets;
                case KeysAndButtons.Backslash:
                    return Keys.OemBackslash;
                case KeysAndButtons.RightBracket:
                    return Keys.OemCloseBrackets;
                case KeysAndButtons.GraveAccent:
                    return Keys.OemTilde;
                case KeysAndButtons.Escape:
                    return Keys.Escape;
                case KeysAndButtons.Enter:
                    return Keys.Enter;
                case KeysAndButtons.Tab:
                    return Keys.Tab;
                case KeysAndButtons.Backspace:
                    return Keys.Back;
                case KeysAndButtons.Insert:
                    return Keys.Insert;
                case KeysAndButtons.Delete:
                    return Keys.Delete;
                case KeysAndButtons.Right:
                    return Keys.Right;
                case KeysAndButtons.Left:
                    return Keys.Left;
                case KeysAndButtons.Down:
                    return Keys.Down;
                case KeysAndButtons.Up:
                    return Keys.Up;
                case KeysAndButtons.PageUp:
                    return Keys.PageUp;
                case KeysAndButtons.PageDown:
                    return Keys.PageDown;
                case KeysAndButtons.Home:
                    return Keys.Home;
                case KeysAndButtons.End:
                    return Keys.End;
                case KeysAndButtons.CapsLock:
                    return Keys.CapsLock;
                case KeysAndButtons.ScrollLock:
                    return Keys.CapsLock;
                case KeysAndButtons.NumLock:
                    return Keys.NumLock;
                case KeysAndButtons.PrintScreen:
                    return Keys.PrintScreen;
                case KeysAndButtons.Pause:
                    return Keys.Pause;
                case KeysAndButtons.F1:
                    return Keys.F1;
                case KeysAndButtons.F2:
                    return Keys.F2;
                case KeysAndButtons.F3:
                    return Keys.F3;
                case KeysAndButtons.F4:
                    return Keys.F4;
                case KeysAndButtons.F5:
                    return Keys.F5;
                case KeysAndButtons.F6:
                    return Keys.F6;
                case KeysAndButtons.F7:
                    return Keys.F7;
                case KeysAndButtons.F8:
                    return Keys.F8;
                case KeysAndButtons.F9:
                    return Keys.F9;
                case KeysAndButtons.F10:
                    return Keys.F10;
                case KeysAndButtons.F11:
                    return Keys.F11;
                case KeysAndButtons.F12:
                    return Keys.F12;
                case KeysAndButtons.F13:
                    return Keys.F13;
                case KeysAndButtons.F14:
                    return Keys.F14;
                case KeysAndButtons.F15:
                    return Keys.F15;
                case KeysAndButtons.F16:
                    return Keys.F16;
                case KeysAndButtons.F17:
                    return Keys.F17;
                case KeysAndButtons.F18:
                    return Keys.F18;
                case KeysAndButtons.F19:
                    return Keys.F19;
                case KeysAndButtons.F20:
                    return Keys.F20;
                case KeysAndButtons.F21:
                    return Keys.F21;
                case KeysAndButtons.F22:
                    return Keys.F22;
                case KeysAndButtons.F23:
                    return Keys.F23;
                case KeysAndButtons.F24:
                    return Keys.F24;
                case KeysAndButtons.KeypadZero:
                    return Keys.NumPad0;
                case KeysAndButtons.KeypadOne:
                    return Keys.NumPad1;
                case KeysAndButtons.KeypadTwo:
                    return Keys.NumPad2;
                case KeysAndButtons.KeypadThree:
                    return Keys.NumPad3;
                case KeysAndButtons.KeypadFour:
                    return Keys.NumPad4;
                case KeysAndButtons.KeypadFive:
                    return Keys.NumPad5;
                case KeysAndButtons.KeypadSix:
                    return Keys.NumPad6;
                case KeysAndButtons.KeypadSeven:
                    return Keys.NumPad7;
                case KeysAndButtons.KeypadEight:
                    return Keys.NumPad8;
                case KeysAndButtons.KeypadNine:
                    return Keys.NumPad9;
                case KeysAndButtons.KeypadDecimal:
                    return Keys.Decimal;
                case KeysAndButtons.KeypadDivide:
                    return Keys.Divide;
                case KeysAndButtons.KeypadMultiply:
                    return Keys.Multiply;
                case KeysAndButtons.KeypadSubtract:
                    return Keys.Subtract;
                case KeysAndButtons.KeypadAdd:
                    return Keys.Add;
                case KeysAndButtons.KeypadEnter:
                    return Keys.Enter;
                case KeysAndButtons.KeypadEqual:
                    return Keys.OemPlus;
                case KeysAndButtons.LeftShift:
                    return Keys.LeftShift;
                case KeysAndButtons.LeftControl:
                    return Keys.LeftControl;
                case KeysAndButtons.LeftAlt:
                    return Keys.LeftAlt;
                case KeysAndButtons.LeftSuper:
                    return Keys.LeftWindows;
                case KeysAndButtons.RightShift:
                    return Keys.RightShift;
                case KeysAndButtons.RightControl:
                    return Keys.RightControl;
                case KeysAndButtons.RightAlt:
                    return Keys.RightAlt;
                case KeysAndButtons.RightSuper:
                    return Keys.RightWindows;
                default:
                    return Keys.None;
            }
        }
    }
}