using KeysAndButtons = Crystal.Framework.Buttons;
using Microsoft.Xna.Framework.Input;

namespace Crystal.Engine
{
    public static class ButtonsExtensions
    {
        public static KeysAndButtons ToCrystal(this Keys self)
        {
            switch(self)
            {
                case Keys.OemQuotes:
                    return KeysAndButtons.Apostrophe;
                case Keys.OemComma:
                    return KeysAndButtons.Comma;
                case Keys.OemMinus:
                    return KeysAndButtons.Minus;
                case Keys.OemPeriod:
                    return KeysAndButtons.Period;
                case Keys.OemQuestion:
                    return KeysAndButtons.Slash;
                case Keys.D0:
                    return KeysAndButtons.Zero;
                case Keys.D1:
                    return KeysAndButtons.One;
                case Keys.D2:
                    return KeysAndButtons.Two;
                case Keys.D3:
                    return KeysAndButtons.Three;
                case Keys.D4:
                    return KeysAndButtons.Four;
                case Keys.D5:
                    return KeysAndButtons.Five;
                case Keys.D6:
                    return KeysAndButtons.Six;
                case Keys.D7:
                    return KeysAndButtons.Seven;
                case Keys.D8:
                    return KeysAndButtons.Eight;
                case Keys.D9:
                    return KeysAndButtons.Nine;
                case Keys.OemSemicolon:
                    return KeysAndButtons.Semicolon;
                case Keys.OemPlus:
                    return KeysAndButtons.Equal;
                case Keys.A:
                    return KeysAndButtons.A;
                case Keys.B:
                    return KeysAndButtons.B;
                case Keys.C:
                    return KeysAndButtons.C;
                case Keys.D:
                    return KeysAndButtons.D;
                case Keys.E:
                    return KeysAndButtons.E;
                case Keys.F:
                    return KeysAndButtons.F;
                case Keys.G:
                    return KeysAndButtons.G;
                case Keys.H:
                    return KeysAndButtons.H;
                case Keys.I:
                    return KeysAndButtons.I;
                case Keys.J:
                    return KeysAndButtons.J;
                case Keys.K:
                    return KeysAndButtons.K;
                case Keys.L:
                    return KeysAndButtons.L;
                case Keys.M:
                    return KeysAndButtons.M;
                case Keys.N:
                    return KeysAndButtons.N;
                case Keys.O:
                    return KeysAndButtons.O;
                case Keys.P:
                    return KeysAndButtons.P;
                case Keys.Q:
                    return KeysAndButtons.Q;
                case Keys.R:
                    return KeysAndButtons.R;
                case Keys.S:
                    return KeysAndButtons.S;
                case Keys.T:
                    return KeysAndButtons.T;
                case Keys.U:
                    return KeysAndButtons.U;
                case Keys.V:
                    return KeysAndButtons.V;
                case Keys.W:
                    return KeysAndButtons.W;
                case Keys.X:
                    return KeysAndButtons.X;
                case Keys.Y:
                    return KeysAndButtons.Y;
                case Keys.Z:
                    return KeysAndButtons.Z;
                case Keys.OemOpenBrackets:
                    return KeysAndButtons.LeftBracket;
                case Keys.OemBackslash:
                    return KeysAndButtons.Backslash;
                case Keys.OemCloseBrackets:
                    return KeysAndButtons.RightBracket;
                case Keys.OemTilde:
                    return KeysAndButtons.GraveAccent;
                case Keys.Escape:
                    return KeysAndButtons.Escape;
                case Keys.Enter:
                    return KeysAndButtons.Enter;
                case Keys.Tab:
                    return KeysAndButtons.Tab;
                case Keys.Back:
                    return KeysAndButtons.Backspace;
                case Keys.Insert:
                    return KeysAndButtons.Insert;
                case Keys.Delete:
                    return KeysAndButtons.Delete;
                case Keys.Right:
                    return KeysAndButtons.Right;
                case Keys.Left:
                    return KeysAndButtons.Left;
                case Keys.Down:
                    return KeysAndButtons.Down;
                case Keys.Up:
                    return KeysAndButtons.Up;
                case Keys.PageUp:
                    return KeysAndButtons.PageUp;
                case Keys.PageDown:
                    return KeysAndButtons.PageDown;
                case Keys.Home:
                    return KeysAndButtons.Home;
                case Keys.End:
                    return KeysAndButtons.End;
                case Keys.CapsLock:
                    return KeysAndButtons.CapsLock;
                case Keys.Scroll:
                    return KeysAndButtons.ScrollLock;
                case Keys.NumLock:
                    return KeysAndButtons.NumLock;
                case Keys.PrintScreen:
                    return KeysAndButtons.PrintScreen;
                case Keys.Pause:
                    return KeysAndButtons.Pause;
                case Keys.F1:
                    return KeysAndButtons.F1;
                case Keys.F2:
                    return KeysAndButtons.F2;
                case Keys.F3:
                    return KeysAndButtons.F3;
                case Keys.F4:
                    return KeysAndButtons.F4;
                case Keys.F5:
                    return KeysAndButtons.F5;
                case Keys.F6:
                    return KeysAndButtons.F6;
                case Keys.F7:
                    return KeysAndButtons.F7;
                case Keys.F8:
                    return KeysAndButtons.F8;
                case Keys.F9:
                    return KeysAndButtons.F9;
                case Keys.F10:
                    return KeysAndButtons.F10;
                case Keys.F11:
                    return KeysAndButtons.F11;
                case Keys.F12:
                    return KeysAndButtons.F12;
                case Keys.F13:
                    return KeysAndButtons.F13;
                case Keys.F14:
                    return KeysAndButtons.F14;
                case Keys.F15:
                    return KeysAndButtons.F15;
                case Keys.F16:
                    return KeysAndButtons.F16;
                case Keys.F17:
                    return KeysAndButtons.F17;
                case Keys.F18:
                    return KeysAndButtons.F18;
                case Keys.F19:
                    return KeysAndButtons.F19;
                case Keys.F20:
                    return KeysAndButtons.F20;
                case Keys.F21:
                    return KeysAndButtons.F21;
                case Keys.F22:
                    return KeysAndButtons.F22;
                case Keys.F23:
                    return KeysAndButtons.F23;
                case Keys.F24:
                    return KeysAndButtons.F24;
                case Keys.NumPad0:
                    return KeysAndButtons.KeypadZero;
                case Keys.NumPad1:
                    return KeysAndButtons.KeypadOne;
                case Keys.NumPad2:
                    return KeysAndButtons.KeypadTwo;
                case Keys.NumPad3:
                    return KeysAndButtons.KeypadThree;
                case Keys.NumPad4:
                    return KeysAndButtons.KeypadFour;
                case Keys.NumPad5:
                    return KeysAndButtons.KeypadFive;
                case Keys.NumPad6:
                    return KeysAndButtons.KeypadSix;
                case Keys.NumPad7:
                    return KeysAndButtons.KeypadSeven;
                case Keys.NumPad8:
                    return KeysAndButtons.KeypadEight;
                case Keys.NumPad9:
                    return KeysAndButtons.KeypadNine;
                case Keys.Decimal:
                    return KeysAndButtons.KeypadDecimal;
                case Keys.Divide:
                    return KeysAndButtons.KeypadDivide;
                case Keys.Multiply:
                    return KeysAndButtons.KeypadMultiply;
                case Keys.Subtract:
                    return KeysAndButtons.KeypadSubtract;
                case Keys.Add:
                    return KeysAndButtons.KeypadAdd;
                case Keys.LeftShift:
                    return KeysAndButtons.LeftShift;
                case Keys.LeftControl:
                    return KeysAndButtons.LeftControl;
                case Keys.LeftAlt:
                    return KeysAndButtons.LeftAlt;
                case Keys.LeftWindows:
                    return KeysAndButtons.LeftSuper;
                case Keys.RightShift:
                    return KeysAndButtons.RightShift;
                case Keys.RightControl:
                    return KeysAndButtons.RightControl;
                case Keys.RightAlt:
                    return KeysAndButtons.RightAlt;
                case Keys.RightWindows:
                    return KeysAndButtons.RightSuper;
                default:
                    return KeysAndButtons.None;
            }
        }

        public static Keys ToMonoGame(this KeysAndButtons self)
        {
            switch(self)
            {
                case KeysAndButtons.Apostrophe:
                    return Keys.OemQuotes;
                case KeysAndButtons.Comma:
                    return Keys.OemComma;
                case KeysAndButtons.Minus:
                    return Keys.OemMinus;
                case KeysAndButtons.Period:
                    return Keys.OemPeriod;
                case KeysAndButtons.Slash:
                    return Keys.OemQuestion;
                case KeysAndButtons.Zero:
                    return Keys.D0;
                case KeysAndButtons.One:
                    return Keys.D1;
                case KeysAndButtons.Two:
                    return Keys.D2;
                case KeysAndButtons.Three:
                    return Keys.D3;
                case KeysAndButtons.Four:
                    return Keys.D4;
                case KeysAndButtons.Five:
                    return Keys.D5;
                case KeysAndButtons.Six:
                    return Keys.D6;
                case KeysAndButtons.Seven:
                    return Keys.D7;
                case KeysAndButtons.Eight:
                    return Keys.D8;
                case KeysAndButtons.Nine:
                    return Keys.D9;
                case KeysAndButtons.Semicolon:
                    return Keys.OemSemicolon;
                case KeysAndButtons.Equal:
                    return Keys.OemPlus;
                case KeysAndButtons.A:
                    return Keys.A;
                case KeysAndButtons.B:
                    return Keys.B;
                case KeysAndButtons.C:
                    return Keys.C;
                case KeysAndButtons.D:
                    return Keys.D;
                case KeysAndButtons.E:
                    return Keys.E;
                case KeysAndButtons.F:
                    return Keys.F;
                case KeysAndButtons.G:
                    return Keys.G;
                case KeysAndButtons.H:
                    return Keys.H;
                case KeysAndButtons.I:
                    return Keys.I;
                case KeysAndButtons.J:
                    return Keys.J;
                case KeysAndButtons.K:
                    return Keys.K;
                case KeysAndButtons.L:
                    return Keys.L;
                case KeysAndButtons.M:
                    return Keys.M;
                case KeysAndButtons.N:
                    return Keys.N;
                case KeysAndButtons.O:
                    return Keys.O;
                case KeysAndButtons.P:
                    return Keys.P;
                case KeysAndButtons.Q:
                    return Keys.Q;
                case KeysAndButtons.R:
                    return Keys.R;
                case KeysAndButtons.S:
                    return Keys.S;
                case KeysAndButtons.T:
                    return Keys.T;
                case KeysAndButtons.U:
                    return Keys.U;
                case KeysAndButtons.V:
                    return Keys.V;
                case KeysAndButtons.W:
                    return Keys.W;
                case KeysAndButtons.X:
                    return Keys.X;
                case KeysAndButtons.Y:
                    return Keys.Y;
                case KeysAndButtons.Z:
                    return Keys.Z;
                case KeysAndButtons.LeftBracket:
                    return Keys.OemOpenBrackets;
                case KeysAndButtons.Backslash:
                    return Keys.OemBackslash;
                case KeysAndButtons.RightBracket:
                    return Keys.OemCloseBrackets;
                case KeysAndButtons.GraveAccent:
                    return Keys.OemTilde;
                case KeysAndButtons.Escape:
                    return Keys.Escape;
                case KeysAndButtons.Enter:
                    return Keys.Enter;
                case KeysAndButtons.Tab:
                    return Keys.Tab;
                case KeysAndButtons.Backspace:
                    return Keys.Back;
                case KeysAndButtons.Insert:
                    return Keys.Insert;
                case KeysAndButtons.Delete:
                    return Keys.Delete;
                case KeysAndButtons.Right:
                    return Keys.Right;
                case KeysAndButtons.Left:
                    return Keys.Left;
                case KeysAndButtons.Down:
                    return Keys.Down;
                case KeysAndButtons.Up:
                    return Keys.Up;
                case KeysAndButtons.PageUp:
                    return Keys.PageUp;
                case KeysAndButtons.PageDown:
                    return Keys.PageDown;
                case KeysAndButtons.Home:
                    return Keys.Home;
                case KeysAndButtons.End:
                    return Keys.End;
                case KeysAndButtons.CapsLock:
                    return Keys.CapsLock;
                case KeysAndButtons.ScrollLock:
                    return Keys.Scroll;
                case KeysAndButtons.NumLock:
                    return Keys.NumLock;
                case KeysAndButtons.PrintScreen:
                    return Keys.PrintScreen;
                case KeysAndButtons.Pause:
                    return Keys.Pause;
                case KeysAndButtons.F1:
                    return Keys.F1;
                case KeysAndButtons.F2:
                    return Keys.F2;
                case KeysAndButtons.F3:
                    return Keys.F3;
                case KeysAndButtons.F4:
                    return Keys.F4;
                case KeysAndButtons.F5:
                    return Keys.F5;
                case KeysAndButtons.F6:
                    return Keys.F6;
                case KeysAndButtons.F7:
                    return Keys.F7;
                case KeysAndButtons.F8:
                    return Keys.F8;
                case KeysAndButtons.F9:
                    return Keys.F9;
                case KeysAndButtons.F10:
                    return Keys.F10;
                case KeysAndButtons.F11:
                    return Keys.F11;
                case KeysAndButtons.F12:
                    return Keys.F12;
                case KeysAndButtons.F13:
                    return Keys.F13;
                case KeysAndButtons.F14:
                    return Keys.F14;
                case KeysAndButtons.F15:
                    return Keys.F15;
                case KeysAndButtons.F16:
                    return Keys.F16;
                case KeysAndButtons.F17:
                    return Keys.F17;
                case KeysAndButtons.F18:
                    return Keys.F18;
                case KeysAndButtons.F19:
                    return Keys.F19;
                case KeysAndButtons.F20:
                    return Keys.F20;
                case KeysAndButtons.F21:
                    return Keys.F21;
                case KeysAndButtons.F22:
                    return Keys.F22;
                case KeysAndButtons.F23:
                    return Keys.F23;
                case KeysAndButtons.F24:
                    return Keys.F24;
                case KeysAndButtons.KeypadZero:
                    return Keys.NumPad0;
                case KeysAndButtons.KeypadOne:
                    return Keys.NumPad1;
                case KeysAndButtons.KeypadTwo:
                    return Keys.NumPad2;
                case KeysAndButtons.KeypadThree:
                    return Keys.NumPad3;
                case KeysAndButtons.KeypadFour:
                    return Keys.NumPad4;
                case KeysAndButtons.KeypadFive:
                    return Keys.NumPad5;
                case KeysAndButtons.KeypadSix:
                    return Keys.NumPad6;
                case KeysAndButtons.KeypadSeven:
                    return Keys.NumPad7;
                case KeysAndButtons.KeypadEight:
                    return Keys.NumPad8;
                case KeysAndButtons.KeypadNine:
                    return Keys.NumPad9;
                case KeysAndButtons.KeypadDecimal:
                    return Keys.Decimal;
                case KeysAndButtons.KeypadDivide:
                    return Keys.Divide;
                case KeysAndButtons.KeypadMultiply:
                    return Keys.Multiply;
                case KeysAndButtons.KeypadSubtract:
                    return Keys.Subtract;
                case KeysAndButtons.KeypadAdd:
                    return Keys.Add;
                case KeysAndButtons.KeypadEnter:
                    return Keys.Enter;
                case KeysAndButtons.KeypadEqual:
                    return Keys.OemPlus;
                case KeysAndButtons.LeftShift:
                    return Keys.LeftShift;
                case KeysAndButtons.LeftControl:
                    return Keys.LeftControl;
                case KeysAndButtons.LeftAlt:
                    return Keys.LeftAlt;
                case KeysAndButtons.LeftSuper:
                    return Keys.LeftWindows;
                case KeysAndButtons.RightShift:
                    return Keys.RightShift;
                case KeysAndButtons.RightControl:
                    return Keys.RightControl;
                case KeysAndButtons.RightAlt:
                    return Keys.RightAlt;
                case KeysAndButtons.RightSuper:
                    return Keys.RightWindows;
                default:
                    return Keys.None;
            }
        }
    }
}