using System;
using Crystal.Framework;
using SFML.Window;

namespace Crystal.Engine.SFML
{
    public static class ButtonsExtensions
    {
        public static Keyboard.Key ToSFML(this Buttons self)
        {
            switch (self)
            {
                case Buttons.None:
                    return Keyboard.Key.Unknown;
                case Buttons.Space:
                    return Keyboard.Key.Space;
                case Buttons.Apostrophe:
                    return Keyboard.Key.Unknown;
                case Buttons.Comma:
                    return Keyboard.Key.Comma;
                case Buttons.Minus:
                    return Keyboard.Key.Hyphen;
                case Buttons.Period:
                    return Keyboard.Key.Period;
                case Buttons.Slash:
                    return Keyboard.Key.Slash;
                case Buttons.Zero:
                    return Keyboard.Key.Num0;
                case Buttons.One:
                    return Keyboard.Key.Num1;
                case Buttons.Two:
                    return Keyboard.Key.Num2;
                case Buttons.Three:
                    return Keyboard.Key.Num3;
                case Buttons.Four:
                    return Keyboard.Key.Num4;
                case Buttons.Five:
                    return Keyboard.Key.Num5;
                case Buttons.Six:
                    return Keyboard.Key.Num6;
                case Buttons.Seven:
                    return Keyboard.Key.Num7;
                case Buttons.Eight:
                    return Keyboard.Key.Num8;
                case Buttons.Nine:
                    return Keyboard.Key.Num9;
                case Buttons.Semicolon:
                    return Keyboard.Key.Semicolon;
                case Buttons.Equal:
                    return Keyboard.Key.Equal;
                case Buttons.A:
                    return Keyboard.Key.A;
                case Buttons.B:
                    return Keyboard.Key.B;
                case Buttons.C:
                    return Keyboard.Key.C;
                case Buttons.D:
                    return Keyboard.Key.D;
                case Buttons.E:
                    return Keyboard.Key.E;
                case Buttons.F:
                    return Keyboard.Key.F;
                case Buttons.G:
                    return Keyboard.Key.G;
                case Buttons.H:
                    return Keyboard.Key.H;
                case Buttons.I:
                    return Keyboard.Key.I;
                case Buttons.J:
                    return Keyboard.Key.J;
                case Buttons.K:
                    return Keyboard.Key.K;
                case Buttons.L:
                    return Keyboard.Key.L;
                case Buttons.M:
                    return Keyboard.Key.M;
                case Buttons.N:
                    return Keyboard.Key.N;
                case Buttons.O:
                    return Keyboard.Key.O;
                case Buttons.P:
                    return Keyboard.Key.P;
                case Buttons.Q:
                    return Keyboard.Key.Q;
                case Buttons.R:
                    return Keyboard.Key.R;
                case Buttons.S:
                    return Keyboard.Key.S;
                case Buttons.T:
                    return Keyboard.Key.T;
                case Buttons.U:
                    return Keyboard.Key.U;
                case Buttons.V:
                    return Keyboard.Key.V;
                case Buttons.W:
                    return Keyboard.Key.W;
                case Buttons.X:
                    return Keyboard.Key.X;
                case Buttons.Y:
                    return Keyboard.Key.Y;
                case Buttons.Z:
                    return Keyboard.Key.Z;
                case Buttons.LeftBracket:
                    return Keyboard.Key.LBracket;
                case Buttons.Backslash:
                    return Keyboard.Key.Backslash;
                case Buttons.RightBracket:
                    return Keyboard.Key.RBracket;
                case Buttons.GraveAccent:
                    return Keyboard.Key.Quote;
                case Buttons.Escape:
                    return Keyboard.Key.Escape;
                case Buttons.Enter:
                    return Keyboard.Key.Enter;
                case Buttons.Tab:
                    return Keyboard.Key.Tab;
                case Buttons.Backspace:
                    return Keyboard.Key.Backspace;
                case Buttons.Insert:
                    return Keyboard.Key.Insert;
                case Buttons.Delete:
                    return Keyboard.Key.Delete;
                case Buttons.Right:
                    return Keyboard.Key.Right;
                case Buttons.Left:
                    return Keyboard.Key.Left;
                case Buttons.Down:
                    return Keyboard.Key.Down;
                case Buttons.Up:
                    return Keyboard.Key.Up;
                case Buttons.PageUp:
                    return Keyboard.Key.PageUp;
                case Buttons.PageDown:
                    return Keyboard.Key.PageDown;
                case Buttons.Home:
                    return Keyboard.Key.Home;
                case Buttons.End:
                    return Keyboard.Key.End;
                case Buttons.CapsLock:
                    return Keyboard.Key.Unknown;
                case Buttons.ScrollLock:
                    return Keyboard.Key.Unknown;
                case Buttons.NumLock:
                    return Keyboard.Key.Unknown;
                case Buttons.PrintScreen:
                    return Keyboard.Key.Unknown;
                case Buttons.Pause:
                    return Keyboard.Key.Pause;
                case Buttons.F1:
                    return Keyboard.Key.F1;
                case Buttons.F2:
                    return Keyboard.Key.F2;
                case Buttons.F3:
                    return Keyboard.Key.F3;
                case Buttons.F4:
                    return Keyboard.Key.F4;
                case Buttons.F5:
                    return Keyboard.Key.F5;
                case Buttons.F6:
                    return Keyboard.Key.F6;
                case Buttons.F7:
                    return Keyboard.Key.F7;
                case Buttons.F8:
                    return Keyboard.Key.F8;
                case Buttons.F9:
                    return Keyboard.Key.F9;
                case Buttons.F10:
                    return Keyboard.Key.F10;
                case Buttons.F11:
                    return Keyboard.Key.F11;
                case Buttons.F12:
                    return Keyboard.Key.F12;
                case Buttons.F13:
                    return Keyboard.Key.F13;
                case Buttons.F14:
                    return Keyboard.Key.F14;
                case Buttons.F15:
                    return Keyboard.Key.F15;
                case Buttons.F16:
                    return Keyboard.Key.Unknown;
                case Buttons.F17:
                    return Keyboard.Key.Unknown;
                case Buttons.F18:
                    return Keyboard.Key.Unknown;
                case Buttons.F19:
                    return Keyboard.Key.Unknown;
                case Buttons.F20:
                    return Keyboard.Key.Unknown;
                case Buttons.F21:
                    return Keyboard.Key.Unknown;
                case Buttons.F22:
                    return Keyboard.Key.Unknown;
                case Buttons.F23:
                    return Keyboard.Key.Unknown;
                case Buttons.F24:
                    return Keyboard.Key.Unknown;
                case Buttons.KeypadZero:
                    return Keyboard.Key.Numpad0;
                case Buttons.KeypadOne:
                    return Keyboard.Key.Numpad1;
                case Buttons.KeypadTwo:
                    return Keyboard.Key.Numpad2;
                case Buttons.KeypadThree:
                    return Keyboard.Key.Numpad3;
                case Buttons.KeypadFour:
                    return Keyboard.Key.Numpad4;
                case Buttons.KeypadFive:
                    return Keyboard.Key.Numpad5;
                case Buttons.KeypadSix:
                    return Keyboard.Key.Numpad6;
                case Buttons.KeypadSeven:
                    return Keyboard.Key.Numpad7;
                case Buttons.KeypadEight:
                    return Keyboard.Key.Numpad8;
                case Buttons.KeypadNine:
                    return Keyboard.Key.Numpad9;
                case Buttons.KeypadDecimal:
                    return Keyboard.Key.Unknown;
                case Buttons.KeypadDivide:
                    return Keyboard.Key.Divide;
                case Buttons.KeypadMultiply:
                    return Keyboard.Key.Multiply;
                case Buttons.KeypadSubtract:
                    return Keyboard.Key.Subtract;
                case Buttons.KeypadAdd:
                    return Keyboard.Key.Add;
                case Buttons.KeypadEnter:
                    return Keyboard.Key.Enter;
                case Buttons.KeypadEqual:
                    return Keyboard.Key.Equal;
                case Buttons.LeftShift:
                    return Keyboard.Key.LShift;
                case Buttons.LeftControl:
                    return Keyboard.Key.LControl;
                case Buttons.LeftAlt:
                    return Keyboard.Key.LAlt;
                case Buttons.LeftSuper:
                    return Keyboard.Key.LSystem;
                case Buttons.RightShift:
                    return Keyboard.Key.RShift;
                case Buttons.RightControl:
                    return Keyboard.Key.RControl;
                case Buttons.RightAlt:
                    return Keyboard.Key.RAlt;
                case Buttons.RightSuper:
                    return Keyboard.Key.RSystem;
                default:
                    return Keyboard.Key.Unknown;
            }
        }

        public static Buttons ToCrystal(this Keyboard.Key self)
        {
            switch (self)
            {
                case Keyboard.Key.Unknown:
                    return Buttons.None;
                case Keyboard.Key.Space:
                    return Buttons.Space;
                case Keyboard.Key.Comma:
                    return Buttons.Comma;
                case Keyboard.Key.Hyphen:
                    return Buttons.Minus;
                case Keyboard.Key.Period:
                    return Buttons.Period;
                case Keyboard.Key.Slash:
                    return Buttons.Slash;
                case Keyboard.Key.Num0:
                    return Buttons.Zero;
                case Keyboard.Key.Num1:
                    return Buttons.One;
                case Keyboard.Key.Num2:
                    return Buttons.Two;
                case Keyboard.Key.Num3:
                    return Buttons.Three;
                case Keyboard.Key.Num4:
                    return Buttons.Four;
                case Keyboard.Key.Num5:
                    return Buttons.Five;
                case Keyboard.Key.Num6:
                    return Buttons.Six;
                case Keyboard.Key.Num7:
                    return Buttons.Seven;
                case Keyboard.Key.Num8:
                    return Buttons.Eight;
                case Keyboard.Key.Num9:
                    return Buttons.Nine;
                case Keyboard.Key.Semicolon:
                    return Buttons.Semicolon;
                case Keyboard.Key.Equal:
                    return Buttons.Equal;
                case Keyboard.Key.A:
                    return Buttons.A;
                case Keyboard.Key.B:
                    return Buttons.B;
                case Keyboard.Key.C:
                    return Buttons.C;
                case Keyboard.Key.D:
                    return Buttons.D;
                case Keyboard.Key.E:
                    return Buttons.E;
                case Keyboard.Key.F:
                    return Buttons.F;
                case Keyboard.Key.G:
                    return Buttons.G;
                case Keyboard.Key.H:
                    return Buttons.H;
                case Keyboard.Key.I:
                    return Buttons.I;
                case Keyboard.Key.J:
                    return Buttons.J;
                case Keyboard.Key.K:
                    return Buttons.K;
                case Keyboard.Key.L:
                    return Buttons.L;
                case Keyboard.Key.M:
                    return Buttons.M;
                case Keyboard.Key.N:
                    return Buttons.N;
                case Keyboard.Key.O:
                    return Buttons.O;
                case Keyboard.Key.P:
                    return Buttons.P;
                case Keyboard.Key.Q:
                    return Buttons.Q;
                case Keyboard.Key.R:
                    return Buttons.R;
                case Keyboard.Key.S:
                    return Buttons.S;
                case Keyboard.Key.T:
                    return Buttons.T;
                case Keyboard.Key.U:
                    return Buttons.U;
                case Keyboard.Key.V:
                    return Buttons.V;
                case Keyboard.Key.W:
                    return Buttons.W;
                case Keyboard.Key.X:
                    return Buttons.X;
                case Keyboard.Key.Y:
                    return Buttons.Y;
                case Keyboard.Key.Z:
                    return Buttons.Z;
                case Keyboard.Key.LBracket:
                    return Buttons.LeftBracket;
                case Keyboard.Key.Backslash:
                    return Buttons.Backslash;
                case Keyboard.Key.RBracket:
                    return Buttons.RightBracket;
                case Keyboard.Key.Quote:
                    return Buttons.GraveAccent;
                case Keyboard.Key.Escape:
                    return Buttons.Escape;
                case Keyboard.Key.Enter:
                    return Buttons.Enter;
                case Keyboard.Key.Tab:
                    return Buttons.Tab;
                case Keyboard.Key.Backspace:
                    return Buttons.Backspace;
                case Keyboard.Key.Insert:
                    return Buttons.Insert;
                case Keyboard.Key.Delete:
                    return Buttons.Delete;
                case Keyboard.Key.Right:
                    return Buttons.Right;
                case Keyboard.Key.Left:
                    return Buttons.Left;
                case Keyboard.Key.Down:
                    return Buttons.Down;
                case Keyboard.Key.Up:
                    return Buttons.Up;
                case Keyboard.Key.PageUp:
                    return Buttons.PageUp;
                case Keyboard.Key.PageDown:
                    return Buttons.PageDown;
                case Keyboard.Key.Home:
                    return Buttons.Home;
                case Keyboard.Key.End:
                    return Buttons.End;
                case Keyboard.Key.Pause:
                    return Buttons.Pause;
                case Keyboard.Key.F1:
                    return Buttons.F1;
                case Keyboard.Key.F2:
                    return Buttons.F2;
                case Keyboard.Key.F3:
                    return Buttons.F3;
                case Keyboard.Key.F4:
                    return Buttons.F4;
                case Keyboard.Key.F5:
                    return Buttons.F5;
                case Keyboard.Key.F6:
                    return Buttons.F6;
                case Keyboard.Key.F7:
                    return Buttons.F7;
                case Keyboard.Key.F8:
                    return Buttons.F8;
                case Keyboard.Key.F9:
                    return Buttons.F9;
                case Keyboard.Key.F10:
                    return Buttons.F10;
                case Keyboard.Key.F11:
                    return Buttons.F11;
                case Keyboard.Key.F12:
                    return Buttons.F12;
                case Keyboard.Key.F13:
                    return Buttons.F13;
                case Keyboard.Key.F14:
                    return Buttons.F14;
                case Keyboard.Key.F15:
                    return Buttons.F15;
                case Keyboard.Key.Numpad0:
                    return Buttons.KeypadZero;
                case Keyboard.Key.Numpad1:
                    return Buttons.KeypadOne;
                case Keyboard.Key.Numpad2:
                    return Buttons.KeypadTwo;
                case Keyboard.Key.Numpad3:
                    return Buttons.KeypadThree;
                case Keyboard.Key.Numpad4:
                    return Buttons.KeypadFour;
                case Keyboard.Key.Numpad5:
                    return Buttons.KeypadFive;
                case Keyboard.Key.Numpad6:
                    return Buttons.KeypadSix;
                case Keyboard.Key.Numpad7:
                    return Buttons.KeypadSeven;
                case Keyboard.Key.Numpad8:
                    return Buttons.KeypadEight;
                case Keyboard.Key.Numpad9:
                    return Buttons.KeypadNine;
                case Keyboard.Key.Divide:
                    return Buttons.KeypadDivide;
                case Keyboard.Key.Multiply:
                    return Buttons.KeypadMultiply;
                case Keyboard.Key.Subtract:
                    return Buttons.KeypadSubtract;
                case Keyboard.Key.Add:
                    return Buttons.KeypadAdd;
                case Keyboard.Key.LShift:
                    return Buttons.LeftShift;
                case Keyboard.Key.LControl:
                    return Buttons.LeftControl;
                case Keyboard.Key.LAlt:
                    return Buttons.LeftAlt;
                case Keyboard.Key.LSystem:
                    return Buttons.LeftSuper;
                case Keyboard.Key.RShift:
                    return Buttons.RightShift;
                case Keyboard.Key.RControl:
                    return Buttons.RightControl;
                case Keyboard.Key.RAlt:
                    return Buttons.RightAlt;
                case Keyboard.Key.RSystem:
                    return Buttons.RightSuper;
                default:
                    return Buttons.None;
            }
        }
    }
}